### ISSUE TITLE
1.13 Flattening Changes

### ISSUE THREAD

**Issue by tryashtar** [tryashtar/singularity#95]
Flattening removes damage values and splits many ideas. The following code changes are required:
* ✔ Remove damage argument from `/give` and `/replaceitem`
* ✔ Add all new block/item IDs
* ✔ Change all new/removed block states
* ✔ Remove obsolete or old IDs
* ✔ Remove NBT from all definitions
* ✔ Remove "parent" definition support (parsing and usage)
* ✔ Pick new bad blocks
* ✔ Remove any item that's the same as a block

**Comment by tryashtar** [comment]
Should be done, may have to make some changes after the changes become live, but this is a good preparation. Thanks @fvbico

**Comment by FVbico** [comment]
"pumpkin_stem:age[0,1,2,3,4,5,6]",
"pumpkin_plant",

you forgot "facing=noth south east west up" for the plants ;)

**Comment by tryashtar** [comment]
Thanks a bunch for looking! Will update
